baseURL = "https://podcast.eventmodeling.org/"
languageCode = "en-us"
title = "The Event Modeling and Event Sourcing Podcast"
enableRobotsTXT = true

[params]
  description = "Your weekly podcast about Event Modeling and Event Sourcing. We bring topics of interest from the world of Event Modeling and Event Sourcing to you."
  authors = ["Adam Dymitruk", "Martin Dilger"] 